driver_plugin: lxc

platforms:
  - name: ubuntu
    driver_config:
      base_container: "ubuntu-1204"
      username: "ubuntu"
      password: "ubuntu"

suites:
  - name: default
    run_list:
      - "recipe[monitor::master]"
      - "recipe[monitor::redis]"
      - "recipe[monitor::rabbitmq]"
