---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-10.04.box
  run_list:
  - recipe[apt]
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box
  run_list:
  - recipe[yum::epel]
- name: centos-5.8
  driver_config:
    box: opscode-centos-5.8
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-5.8.box
  run_list:
  - recipe[yum::epel]
suites:
- name: default
  run_list:
  - recipe[monitor::master]
- name: sandbox
  run_list:
    - recipe[haproxy]
    - recipe[graphite]
    - recipe[monitor::master]
    - recipe[monitor::haproxy]
    - recipe[monitor::redis]
    - recipe[monitor::rabbitmq]
  attributes:
    authorization:
      sudo:
        users: ["kitchen"]
        passwordless: true
        include_sudoers_d: true
    haproxy:
      enable_stats_socket: true
    apache:
      listen_ports: [4000]
    graphite:
      listen_port: 4000
      carbon:
        service_type: "init"
    monitor:
      metric_handlers: ["graphite"]
      additional_client_attributes:
        haproxy_services: "servers-http"
