AllCops:
  Exclude:
    - 'files/default/plugins/*'
    - 'files/default/extensions/*'
    - 'files/default/handlers/*'
    - 'test/integration/*'
    - !ruby/regexp /old_and_unused\.rb$/

# other configuration
# ...

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MethodLength:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SpaceAfterComma:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/Lambda:
  Enabled: false
