AllCops:
  Exclude:
    - vendor/**/*
    - test/**/*
    - bin/**/*
    - files/default/plugins/*
    - files/default/extensions/*
    - files/default/handlers/*
    - files/default/transports/*

# other configuration
# ...

Documentation:
  Enabled: false

AlignParameters:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Max: 60

Style/AsciiComments:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SpaceAfterComma:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/Lambda:
  Enabled: false
