language: ruby
dist: xenial
bundler_args: --without integration
rvm:
  - 2.4.1
env:
  - KITCHEN=default-ubuntu-1404
  - KITCHEN=default-ubuntu-1604
  - KITCHEN=default-centos-7x
  - KITCHEN=server-redis-ubuntu-1404
  - KITCHEN=server-redis-ubuntu-1604
  - KITCHEN=server-redis-centos-7x
  - KITCHEN=client-ubuntu-1404
  - KITCHEN=client-ubuntu-1604
  - KITCHEN=client-centos-7x
  - KITCHEN=client-redis-ubuntu-1404
  - KITCHEN=client-redis-ubuntu-1604
  - KITCHEN=client-redis-centos-7x
before_install:
  - sudo apt-get -qq update
  - gem install bundler -v 1.10.6
  - wget https://packages.chef.io/files/stable/chefdk/2.1.11/ubuntu/16.04/chefdk_2.1.11-1_amd64.deb
  - sudo dpkg -i chefdk_2.1.11-1_amd64.deb
  - wget https://releases.hashicorp.com/vagrant/1.9.8/vagrant_1.9.8_x86_64.deb
  - sudo dpkg -i vagrant_1.9.8_x86_64.deb
  - sudo apt-get install -y lxc
  - sudo apt-get install -y lxctl
  - vagrant plugin install vagrant-lxc
  - sudo vagrant lxc sudoers
  - vagrant plugin install aws
script:
  - cat /etc/os-release
  - foodcritic .
  - rubocop .
  - /opt/chefdk/bin/kitchen test $KITCHEN
