language: ruby
bundler_args: --without integration
rvm:
  - 2.2.5
before_install:
  - gem install bundler -v 1.10.6
  - gem install kitchen
script:
  - foodcritic .
  - rubocop .
  - kitchen converge server-redis-ubuntu-1404
